# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.4.1
    - name: install deps
      run: poetry install --no-root
    - name: Run lint
      run: poetry run task lint
    - name: Run format
      run: poetry run task formatter
    - name: Run Sec
      run: poetry run task security
    - name: Run Tests
      run: poetry run task test
      
        concurrency:
    group: some-group-name
        - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/<path>/example-app/.venv
        key: ${{ runner.os }}-venv
        needs: some-other-job

            
